name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Maven
      uses: stCarolas/setup-maven@v3
      with:
        maven-version: 3.5.4     
    - uses: actions/checkout@v1
    - name: Maven build
      run: mvn clean install
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag c2nashish/project-search-api:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push c2nashish/project-search-api:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag c2nashish/project-search-api:latest
    - name: Push the latest Docker image
      run: docker push c2nashish/project-search-api:latest
      
  sonar:
      name: Test - SonarCloud Scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Set up Maven
          uses: stCarolas/setup-maven@v3
          with:
           maven-version: 3.5.4   
        - uses: actions/checkout@v1
        - name: Maven build
          run: mvn clean install
        - name: Jacoco
          run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:   
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: SonarCloud Scan
          run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
